language: ruby
rvm:
  - '2.4.1'
  - '2.3.0'
  - '2.2.0'
  - '2.1.0'
  - '1.9.0'
addons:
  code_climate:
    repo_token: cdb26718880608c44fda7463511e0151140ade238d92cb1044892472da13ca48
script: bundle exec rake
notifications:
  email: false
before_install:
  - git config --global user.email 'pairsee-test@example.com'
  - git config --global user.name 'pairsee-test'
after_success:
  - bundle exec codeclimate-test-reporter
